### PR TITLE
New app icon

### PR DESCRIPTION
**Pull request by bragefuglseth**
app-banner

Hi!  I noticed that the current app icon of Flowtime looks a little stale and uninteresting. Even though the clock metaphor makes sense, it doesn't really convey what the app does and how useful it is. This isn't just a regular time tracking app, it has a specific goal and purpose! I have designed a new app icon to reflect this. I hope you like it!

| Icon type   | Preview |
| ----------- | ------- |
| Default     | io github diegoivanme flowtime |
| Development | io github diegoivanme flowtime Devel |
| Symbolic    | io github diegoivanme flowtime-symbolic |
| Badge       | logo |

### CODE REVIEW

**Comment by Diego-Ivan** [comment]
Hello there! Sorry for taking a little bit long to reviews this MR. I love the icon!, I think it reflects the concept of the application greatly! I only feel that it would make a little bit more sense that the colours of the icon matched the ones of the application (blue for work stages, green for break stages), although I have to say that the contrast between orange and blue looks good. Let me know what you think 😄

**Comment by bragefuglseth** [comment]
I like the idea! How about this?

Preview

**Comment by bragefuglseth** [comment]
No worried! I’ll push the changes!

**Review by Diego-Ivan — APPROVED** [review]

**Comment by Diego-Ivan** [comment]
Thank you so much for this contribution! I really appreciate it! 😄

**Pull request merged**
